# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "unpublished" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SGNUIKit
        path: |
          dist
          !dist/**/*.md
        retention-days: 1
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: output/test/code-coverage.html
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: SGNUIKit
    - run: npm ci
    - run: npm run gulp:build:free --if-present
